maplibre/maplibre-navigation-android

libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/SnapToRoute.java
Added some validation before using a LineString without coordinates in TurfMeasurement.
=> Prevent ArrayIndexOutOfBoundsException when using TurfMeasurement

libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationHelper.java
Instead of causing an exception when none of the cases match, the `nextManeuverPosition` function returns `null`
=> Fix for nextManeuverPosition exception

libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/SnapToRoute.java
Fixed a crash where an IndexOutOfBoundsException was thrown when the current line string had no coordinates.
=> [Crash fix] IndexOutOfBoundsException fix with currentLineString

libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationMapRoute.java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.style.sources.GeoJsonSource.setGeoJson(com.mapbox.geojson.Feature)' on a null object reference
at com.mapbox.services.android.navigation.v5.navigation.NavigationMapRoute.updateArrowShaftWith(NavigationMapRoute.java:495)
at com.mapbox.services.android.navigation.v5.navigation.NavigationMapRoute.addUpcomingManeuverArrow(NavigationMapRoute.java:355)
at com.mapbox.services.android.navigation.v5.route.MapRouteProgressChangeListener.onProgressChange(MapRouteProgressChangeListener.java:26)
at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:145)
at com.mapbox.services.android.navigation.v5.navigation.RouteProcess …
=> Fixed the crash:

CHANGELOG.md, gradle/dependencies.gradle, gradle/mvn-push-android.gradle, jitpack.yml
It appears that with the update of error prone, the jitpack build was broken and the release 1.2.0 could not be released. This PR fixes the build.
=> Fix Jitpack Release

libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationConverter.java, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/location/replay/ReplayRouteLocationEngine.java
This pull request fixes a small bug of the `RouteReplayLocationEngine`. If there were any waypoints, the route replay was stopping at first one.
=> Resume simulation for multi leg routes

CHANGELOG.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/services/android/navigation/testapp/CustomNavigationNotification.java, app/src/main/java/com/mapbox/services/android/navigation/testapp/MainActivity.java, app/src/main/java/com/mapbox/services/android/navigation/testapp/MockNavigationActivity.kt, app/src/main/java/com/mapbox/services/android/navigation/testapp/NavigationApplication.java, app/src/main/java/com/mapbox/services/android/navigation/testapp/Utils.java, build.gradle, gradle/dependencies.gradle, gradle/dependency-updates.gradle, gradle/mvn-push-android.gradle, gradle/wrapper/gradle-wrapper.properties, libandroid-navigation/build.gradle, libandroid-navigation/src/main/AndroidManifest.xml, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/FasterRouteDetectorTest.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationTest.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationEventDispatcherTest.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationFasterRouteListenerTest.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationHelperTest.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessorTest.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/RouteProcessorThreadListenerTest.java
Fixes #23.
This repo still used jcenter, which recently broke the build. Therefore, we updated the used dependencies, including the build tools and removed jcenter. 
Since the upstream Maplibre removed the accesstoken, we removed them here as well. Since this is a larger change, a review would be welcome, for example @Brammos or @wipfli
=> Update Dependencies including Maplibre

CHANGELOG.md, gradle/dependencies.gradle
This PR updates the Maplibre Dependency to 9.6.0
=> Update to Maplibre 9.6.0

CHANGELOG.md, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ToleranceUtils.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/utils/ToleranceUtilsTest.java
This PR moves the usage of navigation options in ToleranceUtils. 
If you haven't changed the default values from the navigation options, nothing should change, if you have changed the values, the code in the OffrouteDetector did not worked correctly as the constants were used instead of the specified values.
=> Use navigation options in ToleranceUtils

CHANGELOG.md, README.md, app/src/main/java/com/mapbox/services/android/navigation/testapp/MockNavigationActivity.kt, app/src/main/java/com/mapbox/services/android/navigation/testapp/NavigationApplication.java, app/src/main/java/com/mapbox/services/android/navigation/testapp/NavigationSettings.kt, app/src/main/java/com/mapbox/services/android/navigation/testapp/NavigationUIActivity.kt, app/src/main/res/values/styles.xml, gradle/developer-config.gradle
Starting with the sample app is very confusing. There were three places that need to configure to get started.
1. `developer-config.xml`
2. `styles.xml`
3. `NavigationSettings.kt`
I choose the existing `developer-config.xml` to be the complete configuration file. 
A good alternative is to generate `BuildConfig` variables or string resources on Gradle build script. The values can be fetched  from `findProperty(...)`. So the user can use  environment variables or `gradle.properties` to set his fields.
Give me feedback if you prefer the here implemented solution or the build script one. For me it was first only important that they are central.
=> Central configuration file

CHANGELOG.md, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigationOptions.java, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationConstants.java, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetector.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/offroute/OffRouteDetectorTest.java
This will fix the problems described in #58.
Following things are done
1. Improve `movingAwayFromManeuver` logic.
2. Mark `maximumDistanceOffRoute` as deprecated
Instead of removing `maximumDistanceOffRoute` directly, I marked the option as deprecated, while some projects may already use this in their code.
Let me know if I can adjust something more or you find some problem in my code.
=> Improve off route detection

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/services/android/navigation/testapp/MainActivity.java, app/src/main/java/com/mapbox/services/android/navigation/testapp/SnapToRouteNavigationActivity.kt, app/src/main/res/layout/activity_snap_to_route_navigation.xml, app/src/main/res/values/strings.xml
This PR will add some basic route snapping example. It's very simple. The route is fixed and navigation starts automatically.
I need this example as a show case for a bug in the default route snap engine. This is the reason that I will split the markdown documentation and example implementation in two PRs.
=> Add route snap example

libandroid-navigation/src/main/AndroidManifest.xml
From Android 14 on, the foregroundServiceType is mandatory and depending on the maplibre sdk will crash the build if this is not included. The type was introduced with Android 10, but ist backwards compatible as old versions simply ignore unknown fields in the manifest
=> Add foregroundServiceType for forwardsCompatibility

libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationView.java
If you move the map and click on recenter an empty Wayview is shown in the UI. 
This bug is already explained  and fixed in the mapbox version (https://github.com/mapbox/mapbox-navigation-android/pull/2366). 
Just a check before changing the visibility.
=> Fix empty view after recenter in NavigationView

CHANGELOG.md, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationHelper.java, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRouteProcessor.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/navigation/NavigationHelperTest.java
This PR improves progress updates if the user is too far from the route. If the user is further away then 1km from the route, we don't progress along the step anymore.
Before this was done, independent of how far the user is away from the route.
This change should only be relevant if you have a fixed route, if you reroute, once the user if offroute, this should not be a relevant change.
=> Skip calculating step distance when too far away from the step

libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/route/RouteFetcher.java
Think the progress variable here should be the method parameter `routeProgress` rather than class member variable `this.routeProgress`. When buildRequest() is called by findRouteFromRouteProgress(), this.routeProgress = routeProgress. However when it is called by findRouteFrom(), this.routeProgress is not assigned. So when rerouting occurs on off route event, it doesn't take effect.
=> Fix rerouting not take effect on off route event.

app/src/main/java/com/mapbox/services/android/navigation/testapp/NavigationUIActivity.kt
When i check [profile of mapbox api ](https://docs.mapbox.com/help/glossary/routing-profile/), don't find the fastest option. So remove it and use default driving-traffic profile.
=> remove fastest profile because mapbox api doesn't support it

CHANGELOG.md, CONTRIBUTING.md, libandroid-navigation/src/main/AndroidManifest.xml
=> Improve contribution docs + clean up AndroidManifest.xml

CHANGELOG.md, libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/snap/SnapToRoute.java, libandroid-navigation/src/test/java/com/mapbox/services/android/navigation/v5/snap/SnapToRouteTest.java, libandroid-navigation/src/test/resources/directions_three_leg_single_step_route.json
I discovered that legs that contains only a single step will cause a `IndexOutOfBoundsException` crash. 
Cause was only a wrong if-condition. But to prevent a wrong bearing of `0`, I adjust the fetching of the upcoming step.
=> Fix snap-to-route crash

libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/turnlane/TurnLaneViewData.java
We would like to develop a Custom Lane Guidance with a customized design, and we require the `TurnLaneViewData` to achieve this. As a result, we are proposing to make it accessible through the public API and would like to understand why it is currently hidden.
=> Making TurnLaneViewData Public

libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationViewRouter.java, libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/ViewRouteListener.java
This PR updates the access modifiers of `ViewRouteListener` and `NavigationViewRouter`, along with three of its methods (`findRouteFrom`, `updateLocation`), to public. These changes are essential to allow developers to handle rerouting more directly within their applications. Without these modifications, developers are forced to rely on less desirable solutions such as duplicating internal code or employing fragile workarounds. Making these classes and methods public simplifies the development process and enhances the flexibility of the navigation functionality.
I welcome feedback on these changes and am open to discussing alternative approaches. Please share any suggestions or insights you have.
Several useful classes in the library are internal, limiting their direct usability. I’d …
=> Make some navigation classes and methods public for extended usability

maplibre-navigation-core/src/commonMain/kotlin/org/maplibre/navigation/core/navigation/NavigationHelper.kt
This should not be logged on info IMHO as this tends to spam the log and triggers quite frequently if users are offroute.
=> Reduce log level from info to debug

CHANGELOG.md, libandroid-navigation-ui/src/main/java/org/maplibre/navigation/android/navigation/ui/v5/map/MapFpsDelegate.java, libandroid-navigation-ui/src/test/java/org/maplibre/navigation/android/navigation/ui/v5/map/MapFpsDelegateTest.java
Closes #141 
As outlined in https://github.com/maplibre/maplibre-navigation-android/issues/141 this PR should fix the `NullPointerException` being thrown in `MapFpsDelegate`.
=> avoid npe when modifier is null

CHANGELOG.md, app/src/main/AndroidManifest.xml, app/src/main/java/org/maplibre/navigation/android/example/GraphHopperNavigationActivity.kt, app/src/main/java/org/maplibre/navigation/android/example/MainActivity.java, app/src/main/res/values/strings.xml, gradle/developer-config.gradle, sample/android/app/src/main/java/org/maplibre/navigation/sample/android/core/CoreOnlyFragment.kt
this adds a new graphhopper sample using the more powerful `POST /navigate` request. This is the same request format as `POST /route` but with the mapbox compatible response.
Also graphhopper can be used for the multiplatform sample via changing provider="valhalla" to "graphhopper".
Related to https://github.com/maplibre/maplibre-navigation-android/issues/151#issuecomment-2768852723
Not sure why the test / build fails here, but locally `./gradle clean build` is green.
(Please note that I'm not a good Android/Kotlin dev and let me know possible improvements :) )
=> added graphhopper sample

CHANGELOG.md, maplibre-navigation-core/src/iosMain/kotlin/org/maplibre/navigation/core/location/engine/AppleLocationEngine.kt
- If a `getLastLocation` request times out on iOS, make a last resort attempt to retrieve the location directly from the `CLLocationManager` instance
- Store the delegate instance in a value to prevent its deallocation
=> Fallback for timed out GPS fix on iOS
